language: java
jdk:
  - oraclejdk7
after_success:
  - printf "after_success! learning-travis-ci project"
  - ls -la ./target
  - curl http://www.naver.com
deploy:
  provider: openshift
  user: junyoung.plum@gmail.com
  password: w1234567890
  domain: nnoco
  app: travistest
  